/**
 * Data types for AI Analysis
 */

export interface DisasterType {
  value: string;
  label: string;
  description?: string;
}

export const DISASTER_TYPES: DisasterType[] = [
  { 
    value: 'flood', 
    label: 'Flood',
    description: 'Overflow of water that submerges land that is usually dry'
  },
  { 
    value: 'earthquake', 
    label: 'Earthquake',
    description: 'Sudden shaking of the ground caused by movements within the earth\'s crust' 
  },
  { 
    value: 'cyclone', 
    label: 'Cyclone',
    description: 'Large scale air mass characterized by inward spiraling winds' 
  },
  { 
    value: 'drought', 
    label: 'Drought',
    description: 'Extended period of unusually low rainfall leading to water scarcity' 
  },
  { 
    value: 'landslide', 
    label: 'Landslide',
    description: 'Movement of a mass of rock, debris, or earth down a slope' 
  },
  { 
    value: 'heatwave', 
    label: 'Heatwave',
    description: 'Prolonged period of excessively hot weather relative to normal conditions' 
  },
  { 
    value: 'wildfire', 
    label: 'Wildfire',
    description: 'Uncontrolled fire that spreads quickly through vegetation' 
  },
  { 
    value: 'tsunami', 
    label: 'Tsunami',
    description: 'Series of large waves generated by sudden displacement of water' 
  },
  { 
    value: 'epidemic', 
    label: 'Epidemic',
    description: 'Widespread occurrence of an infectious disease' 
  },
];

export interface AnalysisOptions {
  useHistoricalData: boolean;
  detailedResponse: boolean;
  confidenceScores: boolean;
  suggestPreventiveMeasures: boolean;
}

export const DEFAULT_ANALYSIS_OPTIONS: AnalysisOptions = {
  useHistoricalData: true,
  detailedResponse: true,
  confidenceScores: true,
  suggestPreventiveMeasures: true
};
